config/routes.rb
Rails.application.routes.draw do
  # Devise routes for user authentication
  devise_for :users

  root to: 'ships#index'
  resources :ships, only: %i[index show new edit] do
    resources :bookings, only: [:new, :create]
  end
  namespace :my do
    resources :ships, only: %i[new create index new edit]
    resources :bookings, only: %i[index]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Resources routes for ships and nested bookings
  resources :ships do
    resources :bookings, only: %i[new create edit update destroy]
  end

  # Namespace for user-specific resources
  namespace :my do
    resources :ships, only: %i[new create index edit update destroy]
    resources :bookings, only: %i[index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :ship

  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date, :dates_available

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?
    return if end_date >= start_date

    errors.add(:end_date, "must be after the start date")
  end

  def dates_available
    return if start_date.blank? || end_date.blank?
    return unless ship.bookings.where("start_date < ? AND end_date > ?", end_date, start_date).exists?

    errors.add(:base, "dates are not available")
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :ships

  validates :name, presence: true, uniqueness: true
end

app/models/ship.rb
class Ship < ApplicationRecord
  include PgSearch::Model

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_and_belongs_to_many :categories

  AIRPORTS = [
    'Amsterdam', 'Athens', 'Belgrade', 'Berlin', 'Bern', 'Bratislava', 'Brussels',
    'Bucharest', 'Budapest', 'Copenhagen', 'Dublin', 'Helsinki', 'Kiev', 'Lisbon',
    'London', 'Luxembourg', 'Madrid', 'Monaco', 'Oslo', 'Paris', 'Prague', 'Reykjavik', 'Riga',
    'Rome', 'San Marino', 'Sarajevo', 'Stockholm', 'Tallinn', 'Vienna', 'Zagreb'
  ]

  validates :name, :description, :capacity, :price_per_day, :available_from, :available_to, presence: true
  validates :price_per_day, numericality: { greater_than: 0 }
  validate :available_dates_valid

  pg_search_scope :search_by_description, against: :description

  scope :filter_by_capacity, ->(capacity) { where("capacity >= ?", capacity) }
  scope :filter_by_airport, ->(location) { where("location = ?", location) }

  private

  def available_dates_valid
    return if available_from.blank? || available_to.blank?
    return if available_from <= available_to

    errors.add(:available_to, "must be after the available from date")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ships, dependent: :destroy
  has_many :bookings, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :ships
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: %i[edit update destroy]
  before_action :set_ship, only: %i[new create]

  def new
    @booking = @ship.bookings.build
  end

  def create
    @booking = @ship.bookings.build(booking_params)
    @booking.user = current_user
    if @booking.save
      redirect_to my_bookings_path, notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @booking.update(booking_params)
      redirect_to @booking.ship, notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to @booking.ship, notice: 'Booking was successfully deleted.'
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_ship
    @ship = Ship.find(params[:ship_id])
  end

  def booking_params
    params.require(:booking).permit(%i[start_date end_date ship_id])
  end
end

app/controllers/my/bookings_controller.rb
module My
  class BookingsController < ApplicationController

    def show
      ## shows details of specific booking
    end

    def index
      @bookings = current_user.bookings
    end
  end
end

app/controllers/my/ships_controller.rb
module My
  class ShipsController < ApplicationController
    before_action :authenticate_user!

    def index
      @ships = current_user.ships.all
    end

    def new
      @ship = current_user.ships.build
    end

    def create
      @ship = current_user.ships.build(ship_params)
      if @ship.save
        redirect_to my_ships_path, notice: 'Ship was successfully created.'
      else
        flash[:alert] = 'Invalid ship'
        render :new
      end
    end

    private

    def ship_params
      params.require(:ship).permit(:name, :description, :capacity, :price_per_day, :location, :available_from, :available_to)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :find_ship, only: [:show, :edit, :update, :destroy]
  before_action :set_airports, only: [:index]
  before_action :set_categories, only: [:index, :new, :edit]

  def index
    @ships = Ship.all

    @ships = filter_by_capacity(@ships, params[:capacity]) if params[:capacity].present?
    @ships = filter_by_airport(@ships, params[:airport]) if params[:airport].present?
  end

  def new
    @ship = current_user.ships.build
  end

  def create
    @ship = current_user.ships.build(ship_params)
    if @ship.save
      redirect_to ships_path, notice: 'Ship was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @ship.update(ship_params)
      redirect_to @ship, notice: 'Ship was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @ship.destroy
    redirect_to ships_path, notice: 'Ship was successfully deleted.'
  end

  def show
    @image = params[:image_id]
    puts @image
  end

  private

  def ship_params
    params.require(:ship).permit(:name, :description, :price_per_day, :available_from, :available_to)
  end

  def find_ship
    @ship = Ship.find(params[:id])
  end

  def set_airports
    @airports = Ship::AIRPORTS
  end

  def set_categories
    @categories = Category.all
  end

  def filter_by_capacity(ships, capacity)
    ships.filter_by_capacity(capacity)
  end

  def filter_by_airport(ships, airport)
    ships.filter_by_airport(airport)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def image_exists?(image)
    File.exist?(image)
  end
end

app/views/bookings/new.html.erb
<div class="container mt-5 min-vh-100">
  <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/ships" class="link-decoration-none">Spaceships</a></li>
    <li class="breadcrumb-item active" aria-current="page"><%= link_to @ship.name, ship_path(@ship)%></li>
    <li class="breadcrumb-item active" aria-current="page">Book the <%= @ship.name %></li>
  </ol>
</nav>

  <div class="row">
    <div class="col-12 col-md-6 p-4">
      <% if @ship.id >= 1 && @ship.id <= 9 %>
          <%= image_tag("#{@ship.id}.png", alt: 'Spaceship', class: 'card-img-top rounded-top-4') %>
      <% else %>
          <%= image_tag('spaceship_placeholder.jpeg', alt: 'Spaceship', class: 'card-img-top rounded-top-4') %>
      <% end %>
    </div>
    <div class="col-12 col-md-6 p-4">
      <h1 class="h3 fw-bold"><%= @ship.name %> booking form</h1>
      <%= form_with(model: [@ship, @booking], local: true, class: 'form-horizontal') do |form| %>
        <% if @booking.errors.any? %>
          <div class="alert alert-danger">
            <h4>Please check the following errors:</h4>
            <ul>
              <% @booking.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-3">
          <%= form.label :start_date, class: 'form-label' %>
          <%= form.date_field :start_date, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= form.label :end_date, class: 'form-label' %>
          <%= form.date_field :end_date, class: 'form-control' %>
        </div>

        <div class="actions">
          <%= form.submit 'Book Now', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <p>&copy; <%= Time.now.year %> Spaceship Rentals. All rights reserved.</p>
</footer>

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'New Spaceship', new_ship_path %></li>
    <% if user_signed_in? %>
      <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Login', new_user_session_path %></li>
      <li><%= link_to 'Sign Up', new_user_registration_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpaceshipsAirbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>
  <%= render partial: "shared/navigation" %>
  <body class="d-flex flex-column min-vh-100">
    <% if notice %>
      <div class="alert alert-info text-center" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-warning text-center" role="alert">
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
  </body>
   <%= render partial: "shared/footer" %>
</html>

app/views/my/bookings/index.html.erb
<div class="container mt-5 min-vh-100">
    <h1 class="mb-4 fw-bold h3">My bookings</h1>
    <ul class="list-group">
      <% @bookings.each do |booking| %>
        <li class="list-group-item d-flex mt-3">
            <!-- Image Container -->
            <% if booking.ship.id >= 1 && booking.ship.id <= 9 %>
                <%= image_tag("#{booking.ship.id}.png", alt: 'Spaceship',style: 'width: 100px;') %>
            <% else %>
              <%= image_tag('spaceship_placeholder.jpeg', alt: 'Spaceship',style: 'width: 100px;') %>
            <% end %>
            <!-- Details Container -->
            <div class="flex-grow-1 ms-3">
                <p class="mb-1"><%= booking.ship.name %></p>
                <small class="small text-muted">Booked from <%= booking.start_date.strftime('%B %d, %Y') %> to <%= booking.end_date.strftime('%B %d, %Y') %></small>
                <br>
                <small class="small text-muted"><%= booking.ship.price_per_day %> € per day</small>
            </div>
        </li>
      <% end %>
    </ul>
</div>

app/views/my/ships/_form.html.erb
<%= simple_form_for @ship do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :capacity %>
  <%= f.input :price_per_day %>
  <%= f.input :available_from, as: :string, input_html: { class: 'flatpickr' } %>
  <%= f.input :available_to, as: :string, input_html: { class: 'flatpickr' } %>
  <%= f.input :location, collection: @airports, prompt: 'Select an Airport' %>

  <%= f.submit %>
<% end %>

app/views/my/ships/edit.html.erb
<div class="container">
  <h1>Edit Spaceship</h1>
  <%= render 'form', airports: @airports %>
</div>

app/views/my/ships/index.html.erb
<div class="container mt-5 min-vh-100">
  <div class="container">
    <h1 class="h3 fw-bold">Your listed spaceships</h1>
    <div class="row mt-3">
      <% @ships.each_with_index do |ship, index| %>
        <!-- Grid Column -->
        <div class="col-sm-6 col-md-4 col-lg-3 mb-4">
          <!-- Card for each ship -->
          <div class="card h-100 rounded-4 shadow border-none">
            <% if ship.id >= 1 && ship.id <= 9 %>
                <%= image_tag("#{ship.id}.png", alt: 'Spaceship', class: 'card-img-top rounded-top-4', style:'height: 250px;') %>
            <% else %>
              <%= image_tag('spaceship_placeholder.jpeg', alt: 'Spaceship', class: 'card-img-top rounded-top-4', style:'height: 250px;') %>
            <% end %>
            <div class="card-body">
              <%= link_to ship.name, ship_path(ship.id), class: 'text-dark fw-bold' %>
              <p class="card-text"><%= ship.description[0...20] + '...' if ship.description.length > 20 %></p>
              <p class="small text-secondary"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus" viewBox="0 0 16 16">
                <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z"/>
                <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5"/>
              </svg> <span class="text-secondary">Capacity:</span> <span class="text-dark"><%= ship.capacity %></span></p>
                            <p class="small text-secondary"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-fill" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M4 4a4 4 0 1 1 4.5 3.969V13.5a.5.5 0 0 1-1 0V7.97A4 4 0 0 1 4 3.999zm2.493 8.574a.5.5 0 0 1-.411.575c-.712.118-1.28.295-1.655.493a1.3 1.3 0 0 0-.37.265.3.3 0 0 0-.057.09V14l.002.008.016.033a.6.6 0 0 0 .145.15c.165.13.435.27.813.395.751.25 1.82.414 3.024.414s2.273-.163 3.024-.414c.378-.126.648-.265.813-.395a.6.6 0 0 0 .146-.15l.015-.033L12 14v-.004a.3.3 0 0 0-.057-.09 1.3 1.3 0 0 0-.37-.264c-.376-.198-.943-.375-1.655-.493a.5.5 0 1 1 .164-.986c.77.127 1.452.328 1.957.594C12.5 13 13 13.4 13 14c0 .426-.26.752-.544.977-.29.228-.68.413-1.116.558-.878.293-2.059.465-3.34.465s-2.462-.172-3.34-.465c-.436-.145-.826-.33-1.116-.558C3.26 14.752 3 14.426 3 14c0-.599.5-1 .961-1.243.505-.266 1.187-.467 1.957-.594a.5.5 0 0 1 .575.411"/>
              </svg> <span class="text-secondary">This ship has been booked</span> <span class="text-dark"><%= ship.bookings.count %> times</span></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/my/ships/new.html.erb
<div class="container mt-5">
  <div class="row">
    <!-- Left Column for Form -->
    <div class="col-md-6 container bg-white p-5 rounded-4 shadow">
      <h1 class="mb-4 h3 fw-bold text-secondary">List your spaceship</h1>
      <%= form_with(model: @ship, url: my_ships_path, local: true, html: { class: 'needs-validation' }) do |form| %>
        <div class="mb-3">
          <%= form.label :name, class: 'form-label' %>
          <%= form.text_field :name, class: 'form-control', required: true %>
        </div>
        <div class="mb-3">
          <%= form.label :description, class: 'form-label' %>
          <%= form.text_area :description, class: 'form-control', rows: 3, required: true %>
        </div>
        <div class="mb-3">
          <%= form.label :capacity, class: 'form-label' %>
          <%= form.number_field :capacity, class: 'form-control', required: true %>
        </div>
        <div class="mb-3">
          <%= form.label :price_per_day, class: 'form-label' %>
          <%= form.number_field :price_per_day, class: 'form-control', required: true %>
        </div>
        <div class="mb-3">
          <%= form.label :location, class: 'form-label' %>
          <%= form.select :location, options_for_select(Ship::AIRPORTS), {}, { class: 'form-select' } %>
        </div>
        <div class="mb-3">
          <%= form.label :available_from, class: 'form-label' %>
          <%= form.date_select :available_from %>
        </div>
        <div class="mb-3">
          <%= form.label :available_to, class: 'form-label' %>
          <%= form.date_select :available_to %>
        </div>
        <div>
          <%= form.submit class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>

    <!-- Right Column for Spaceship Image or Illustration -->
    <div class="col-md-6 d-flex align-items-center p-5">
      <%= image_tag('spaceship_placeholder.jpeg', alt: 'Spaceship', class: 'rounded shadow-lg img-fluid') %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_footer.html.erb
<footer>
 <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top px-5 m-5">
    <div class="col mb-3">
      <a href="/" class="d-flex align-items-center mb-3 link-body-emphasis text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <p class="text-body-secondary">Spacebnb © 2024</p>
    </div>

    <div class="col mb-3">

    </div>

    <div class="col mb-3">
      <h5>Spacebnb</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><%= link_to "Home", root_path, class: "nav-link p-0 text-body-secondary"%></li>
        <% if current_user %>
          <li class="nav-item mb-2 text-danger"><%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link p-0 text-danger" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</footer>

app/views/shared/_navigation.html.erb
<header class="p-3 border border-1">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <% unless current_user.nil? %>
          <li><%= link_to "Browse spaceships", ships_path, class: 'nav-link text-dark fw-bold' %></li>
          <li><%= link_to "My listed spaceships", my_ships_path, class: 'nav-link text-dark fw-bold' %></li>
        <% end %>
          </ul>
        <% if current_user.nil? %>
            <div class="d-flex justify-content-end">
              <%= button_to "Login", new_user_session_path, class: "btn btn-dark me-2 rounded-4" %>
              <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary rounded-4" %>
            </div>
        <% else %>
          <div class="text-end mx-5">
            <%= link_to "My bookings", my_bookings_path, class: "btn btn-dark me-2 rounded-4" %>
            <%= link_to "List my Spaceship", new_my_ship_path, class: 'btn btn-primary rounded-4' %>
          </div>
        <% end %>
      </div>
  </header>

app/views/ships/index.html.erb
<div class="container mt-5 min-vh-100">
  <% if current_user.nil? %>
  <div class="px-4 py-5 my-5 text-center">
    <%= image_tag('rocket_logo.png', alt: 'Spaceship', class: 'd-block mx-auto mb-4', width: '72', height: '57') %>
    <h1 class="display-5 fw-bold text-body-emphasis">Spacebnb</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">Welcome aboard SpacBnB, your gateway to the stars! ✨
        Find the perfect spaceship for your journey. Explore new planets, star systems, and experiences beyond the ordinary, all from the comfort of a spaceship that feels like home.</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
          <%= link_to "Login", new_user_session_path, class: "btn btn-lg btn-dark px-4 gap-3 rounded-4" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-lg btn-primary px-4 rounded-4" %>
      </div>
    </div>
  </div>
  <% else %>
<div class="container m-2 rounded-5">

<%= form_with url: ships_path, method: :get, local: true, html: { class: 'row bg-white p-4 rounded-5 shadow-sm' } do |form| %>
  <!-- Capacity Field -->
  <div class="form-group row col-12 rounded-4 p-3">
    <%= label_tag :capacity, "Filter by capacity", class: 'col-sm-3 col-form-label fw-bold' %>
    <div class="col-sm-9 w-25">
      <%= number_field_tag :capacity, params[:capacity], min: 4, max: 20, class: 'form-control' %>
    </div>
  </div>

  <!-- Airport Field -->
  <div class="form-group row col-12 rounded-4 p-3">
    <%= label_tag :airport, "Filter by airport", class: 'col-sm-3 col-form-label fw-bold' %>
    <div class="col-sm-9 w-25">
      <%= select_tag :airport, options_for_select(@airports.map { |airport| [airport, airport] }, selected: params[:airport]), include_blank: 'Select an Airport', class: 'form-control' %>
    </div>
  </div>

  <!-- Submit Button -->
  <div class="form-group row col-12 rounded-4 p-3">
    <%= submit_tag "Filter", class: 'btn btn-primary' %>
  </div>
<% end %>


  <div class="container mt-5">
    <h1 class="h3 col-12 fw-bold">Browse Spaceships</h1>
    <hr>
    <!-- Grid Row -->
    <div class="row mt-3">
      <% @ships.each_with_index do |ship, index| %>
        <!-- Grid Column -->
        <div class="col-sm-6 col-md-4 col-lg-3 mb-4">
          <!-- Card for each ship -->
          <div class="card h-100 rounded-4 shadow border-none">
            <% if ship.id >= 1 && ship.id <= 9 %>
                <%= image_tag("#{ship.id}.png", alt: 'Spaceship', class: 'card-img-top rounded-top-4', style:'height: 250px;') %>
            <% else %>
              <%= image_tag('spaceship_placeholder.jpeg', alt: 'Spaceship', class: 'card-img-top rounded-top-4', style:'height: 250px;') %>
            <% end %>
            <div class="card-body">
              <%= link_to ship.name, ship_path(ship.id), class: 'text-dark fw-bold' %>
              <p class="card-text"><%= ship.description[0...20] + '...' if ship.description.length > 20 %></p>
              <p class="small text-secondary"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus" viewBox="0 0 16 16">
                <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z"/>
                <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5"/>
              </svg> <span class="text-secondary">Capacity:</span> <span class="text-dark"><%= ship.capacity %></span></p>
                            <p class="small text-secondary"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-fill" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M4 4a4 4 0 1 1 4.5 3.969V13.5a.5.5 0 0 1-1 0V7.97A4 4 0 0 1 4 3.999zm2.493 8.574a.5.5 0 0 1-.411.575c-.712.118-1.28.295-1.655.493a1.3 1.3 0 0 0-.37.265.3.3 0 0 0-.057.09V14l.002.008.016.033a.6.6 0 0 0 .145.15c.165.13.435.27.813.395.751.25 1.82.414 3.024.414s2.273-.163 3.024-.414c.378-.126.648-.265.813-.395a.6.6 0 0 0 .146-.15l.015-.033L12 14v-.004a.3.3 0 0 0-.057-.09 1.3 1.3 0 0 0-.37-.264c-.376-.198-.943-.375-1.655-.493a.5.5 0 1 1 .164-.986c.77.127 1.452.328 1.957.594C12.5 13 13 13.4 13 14c0 .426-.26.752-.544.977-.29.228-.68.413-1.116.558-.878.293-2.059.465-3.34.465s-2.462-.172-3.34-.465c-.436-.145-.826-.33-1.116-.558C3.26 14.752 3 14.426 3 14c0-.599.5-1 .961-1.243.505-.266 1.187-.467 1.957-.594a.5.5 0 0 1 .575.411"/>
              </svg> <span class="text-secondary">Location:</span> <span class="text-dark"><%= ship.location %></span></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

  <% end %>
</div>

app/views/ships/show.html.erb
<div class="container mt-5 min-vh-100">
  <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/ships" class="link-decoration-none">Spaceships</a></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @ship.name %></li>
  </ol>
</nav>

  <div class="row">
    <div class="col-12 col-md-6 p-4">
      <% if @ship.id >= 1 && @ship.id <= 9 %>
          <%= image_tag("#{@ship.id}.png", alt: 'Spaceship', class: 'card-img-top rounded-top-4') %>
      <% else %>
          <%= image_tag('spaceship_placeholder.jpeg', alt: 'Spaceship', class: 'card-img-top rounded-top-4') %>
      <% end %>
    </div>
    <div class="col-12 col-md-6 p-4">
      <h1 class="h3 fw-bold"><%= @ship.name %></h1>
      <p><%= @ship.description %></p>
      <ul class="list-unstyled">
        <li><strong>Price per Day:</strong> $<%= number_with_precision(@ship.price_per_day, precision: 2) %></li>
        <li><strong>Capacity:</strong> <%= @ship.capacity %> people</li>
        <li><strong>Location:</strong> <%= @ship.location %></li>
        <li><strong>Available From:</strong> <%= @ship.available_from.strftime("%B %d, %Y") %></li>
        <li><strong>Available To:</strong> <%= @ship.available_to.strftime("%B %d, %Y") %></li>
      </ul>
      <%= link_to 'Book This Ship', new_ship_booking_path(@ship), class: 'btn btn-primary rounded-4 fw-bold' %>
    </div>
  </div>
</div>